### **1. Indicizzazione booleana**

1. Creare un nuovo vettore con tutti i numeri primi tra 0 e 20. I numeri primi compresi tra 0 e 20 sono: **2, 3, 5, 7, 11, 13, 17, 19**.

2. Utilizza un test logico (ad esempio `>`, `<`, `==`, `!=`) per **selezionare tutte le voci del vettore maggiori di 10**.

3. Utilizza un test logico per selezionare **tutti i numeri primi pari** dalla lista.  


In [17]:
import numpy as np

numeri_primi = np.array([2, 3, 5, 7, 11, 13, 17, 19])
print("Numeri primi tra 0 e 20:", numeri_primi, "\n")

sopra_10 = numeri_primi[numeri_primi > 10]
print("Primi > 10:", sopra_10, "\n")

pari_primi = numeri_primi[numeri_primi % 2 == 0]
print("Primi pari:", pari_primi)



Numeri primi tra 0 e 20: [ 2  3  5  7 11 13 17 19] 

Primi > 10: [11 13 17 19] 

Primi pari: [2]


### **2.  Operazioni su array**
Crea un array **a**, 2D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente la sua 2ª e 4ª riga, e **c** contenente solo la 3ª.  Dividi ogni colonna dell'array a, elemento per elemento, con l'array c.

In [18]:
a = np.arange(1, 21).reshape(5, 4)
print("Array a:\n", a, "\n")

b = a[[1, 3], :]
print("b (2ª e 4ª riga):\n", b, "\n")

c = a[2, :]
print("c (3ª riga):", c, "\n")

divisione = a / c
print("a diviso per c:\n", divisione)
      


Array a:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]] 

b (2ª e 4ª riga):
 [[ 5  6  7  8]
 [13 14 15 16]] 

c (3ª riga): [ 9 10 11 12] 

a diviso per c:
 [[0.11111111 0.2        0.27272727 0.33333333]
 [0.55555556 0.6        0.63636364 0.66666667]
 [1.         1.         1.         1.        ]
 [1.44444444 1.4        1.36363636 1.33333333]
 [1.88888889 1.8        1.72727273 1.66666667]]


### **3. Seleziona il numero più vicino a 0.5 in un array casuale**
Genera un array 10 x 3 con numeri casuali nell'intervallo [0,1].
Per ogni riga, seleziona il numero più vicino a 0.5. Per farlo usa il fancy indexing.

In [20]:
np.random.seed(42)
matrice = np.random.rand(10, 3)
print("Array 10x3 casuale:\n", matrice, "\n")

distanza = np.abs(matrice - 0.5)

colonne_minime = distanza.argmin(axis=1)

righe = np.arange(matrice.shape[0])
vicini = matrice[righe, colonne_minime]

print("Valori più vicini a 0.5 per riga:", vicini)


Array 10x3 casuale:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]
 [0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378]
 [0.51423444 0.59241457 0.04645041]] 

Valori più vicini a 0.5 per riga: [0.37454012 0.59865848 0.60111501 0.70807258 0.21233911 0.52475643
 0.43194502 0.36636184 0.45606998 0.51423444]


### **4. Analisi della Frequenza Cardiaca con NumPy**

1. **Supponiamo che i seguenti valori rappresentino la tua frequenza cardiaca** registrata dal tuo Fitbit durante la giornata:  
   `68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70`  
   Inserisci questi valori in un array NumPy.

2. **Trova la frequenza cardiaca minima** registrata durante la giornata.  
   _(Questo valore rappresenta approssimativamente la tua frequenza cardiaca a riposo, un comune indicatore di salute.)_

3. **Trova la frequenza cardiaca massima** registrata durante la giornata.  
   _(Questo valore è un'indicazione dell'intensità dell'esercizio fisico.)_

4. **Calcoliamo la percentuale di letture effettuate mentre stavi facendo esercizio fisico (frequenza cardiaca sopra a 120)**:  
   - Crea un nuovo array che contiene `True` quando la frequenza cardiaca è **superiore a 120**, e `False` quando è **inferiore o uguale a 120**.
   - Utilizza una funzione di sintesi per calcolare la percentuale di osservazioni in cui la tua frequenza cardiaca era sopra 120.


In [21]:
frequenze = np.array([
    68, 65, 77, 110, 160, 161, 162, 161, 160,
    161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70
])
print("Frequenze registrate:", frequenze, "\n")

min_frequenza = frequenze.min()
print("Frequenza minima:", min_frequenza, "\n")

max_frequenza = frequenze.max()
print("Frequenza massima:", max_frequenza, "\n")

sopra_120 = frequenze > 120
percentuale = sopra_120.sum() / len(frequenze) * 100
print("Percentuale sopra 120 bpm:", round(percentuale, 2), "%")


Frequenze registrate: [ 68  65  77 110 160 161 162 161 160 161 162 163 164 163 162 100  90  97
  72  60  70] 

Frequenza minima: 60 

Frequenza massima: 164 

Percentuale sopra 120 bpm: 52.38 %


### **5. Manipolazione di vettori**

1. Creare un vettore contenente i seguenti stipendi: **50.000, 105.250, 55.000, 89.000**.  
Qual è il costo totale del personale (somma di tutti gli stipendi dell'azienda)?

2. Supponiamo che il nostro malvagio CEO abbia deciso di darsi un aumento.  
Modifica il vettore degli stipendi in modo che il CEO, la persona che guadagna **105.250 dollari**, riceva un aumento del **15%**.

3. Il **115%** di **105.250 dollari** è **121.037,50 dollari**.  
Questo valore è presente nel tuo array? Se no, riesci a capire il motivo?

4. Ricrea il vettore e utilizza l'argomento **`dtype`** in modo che, quando il CEO riceve un aumento del **15%**, il suo stipendio finale sia esattamente **121.037,50 dollari**.

5. Questo aumento ha infastidito l'impiegata con lo stipendio più basso (**50.000 dollari**), che ora pretende un aumento del **20%**.  
Modifica il vettore per riflettere questo cambiamento.

6. L'aumento dato al CEO e all'impiegata ha irritato gli altri due dipendenti, quindi ora devono ricevere un aumento del **10%**.  
Modifica il vettore di conseguenza.

7. Calcola il **costo totale del personale** dopo tutti gli aumenti.  
Alla fine, quanto è costato all'azienda l'aumento di circa **16.000 dollari** del CEO?


In [23]:
stipendi = np.array([50000, 105250, 55000, 89000], dtype=np.float64)
print("Stipendi iniziali:", stipendi, "\n")

stipendi[stipendi == 105250] *= 1.15
print("Dopo aumento CEO:", stipendi, "\n")

presente = 121037.50 in stipendi
print("121037.50 è presente?", presente, "\n")

stipendi = np.array([50000, 105250, 55000, 89000], dtype=np.float64)
stipendi[stipendi == 105250] = 121037.50
print("CEO con stipendio esatto:", stipendi, "\n")

indice_min = stipendi.argmin()
stipendi[indice_min] *= 1.2
print("Dopo aumento impiegata:", stipendi, "\n")

for i in range(len(stipendi)):
    if i != indice_min and stipendi[i] != 121037.50:
        stipendi[i] *= 1.10
print("Dopo aumento generale:", stipendi, "\n")

totale = stipendi.sum()
extra_ceo = 121037.50 - 105250
print("Totale stipendi finale:", totale, "\n")
print("Costo extra CEO:", round(extra_ceo, 2))


Stipendi iniziali: [ 50000. 105250.  55000.  89000.] 

Dopo aumento CEO: [ 50000.  121037.5  55000.   89000. ] 

121037.50 è presente? False 

CEO con stipendio esatto: [ 50000.  121037.5  55000.   89000. ] 

Dopo aumento impiegata: [ 60000.  121037.5  55000.   89000. ] 

Dopo aumento generale: [ 60000.  121037.5  60500.   97900. ] 

Totale stipendi finale: 339437.5 

Costo extra CEO: 15787.5


### **6. Valori di Co2**

1. Carica tramite numpy il file generato e salvato a lezione sulle emissioni di CO2

2. Calcola quanti valori ci CO2 sono sopra la soglia di 18  tonnellate per anno ed il loro valore medio

3. Calcola la frazione totale di emissione sopra la soglia (somma totale sopra la soglia/somma totale)

In [26]:
co2 = np.loadtxt("dati/emissioni.txt")  

sopra_18 = co2[co2 > 18]
print("Num valori sopra 18:", sopra_18.size, "\n")
print("Media valori sopra 18:", round(sopra_18.mean(), 2), "\n")


frazione = sopra_18.sum() / co2.sum()
print("Frazione emissione sopra soglia:", round(frazione, 4))


Num valori sopra 18: 23 

Media valori sopra 18: 18.94 

Frazione emissione sopra soglia: 0.1874


### **7. Analisi di una matrice**
Data la matrice survey con età, reddito e anni di istruzione

survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])


1. Seleziona dalla matrice solo gli intervistati con **almeno 12 anni di istruzione** utilizzando un test logico.

2. In un'unica riga di codice, seleziona i **redditi** degli intervistati con **almeno 12 anni di istruzione**.

3. In un'unica riga di codice, calcola il **reddito medio** degli intervistati con **almeno 12 anni di istruzione**.


In [27]:
survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])

filtro_istruzione = survey_matrix[:, 2] >= 12
selezionati = survey_matrix[filtro_istruzione]
print("Intervistati con >= 12 anni di istruzione:\n", selezionati, "\n")

redditi_filtrati = survey_matrix[survey_matrix[:, 2] >= 12][:, 1]
print("Redditi (>=12 anni istr.):", redditi_filtrati, "\n")

media_redditi = redditi_filtrati.mean()
print("Reddito medio (>=12 anni istr.):", media_redditi)


Intervistati con >= 12 anni di istruzione:
 [[   32 52000    12]
 [   40 63000    14]
 [   35 58000    13]] 

Redditi (>=12 anni istr.): [52000 63000 58000] 

Reddito medio (>=12 anni istr.): 57666.666666666664


### **8. Rimpiazzare gli outliers**

Vediamo se possiamo ripulire alcuni dati mancanti. Immagina di essere il responsabile dei registri di un comune locale con **500 cittadini** di **55 anni e oltre**.  

La città è famosa per la sua longevità e un team di ricercatori ti ha chiesto di identificare **il cittadino più anziano**.  

Il problema è che, occasionalmente, nei registri si verificano errori e in quei casi viene inserita l'età **999** invece dell'età corretta.  

Rimuovi i dati errati dall'array e determina l'età del cittadino più anziano.


In [28]:
ages = np.array([92, 108, 75, 63, 62, 66, 90, 98, 97, 92, 60, 107, 90, 71, 97, 86, 55, 55,
                 98, 57, 96, 104, 96, 94, 72, 98, 111, 98, 89, 69, 77, 92, 85, 101, 93, 100,
                 90, 101, 96, 98, 999, 87, 106, 86, 108, 55, 67, 65, 68, 59, 67, 72, 57, 79,
                 95, 67, 86, 70, 91, 111, 67, 75, 59, 88, 90, 99, 94, 65, 111, 103, 100, 70,
                 63, 65, 100, 110, 999, 70, 57, 75, 56, 104, 111, 90, 74, 100, 90, 86, 88, 99,
                 58, 103, 88, 103, 64, 96, 105, 89, 83, 65, 100, 62, 73, 105, 83, 105, 58, 96,
                 77, 74, 95, 109, 91, 101, 91, 999, 63, 111, 97, 108, 75, 77, 73, 58, 94, 83,
                 90, 61, 110, 107, 105, 85, 64, 66, 71, 107, 105, 72, 78, 66, 100, 102, 72, 999,
                 74, 68, 73, 72, 90, 93, 99, 55, 92, 83, 58, 71, 89, 75, 98, 87, 999, 78,
                 97, 71, 106, 83, 58, 81, 100, 72, 93, 70, 65, 60, 95, 107, 94, 77, 87, 90,
                 82, 56, 99, 107, 86, 56, 73, 96, 64, 69, 64, 92, 57, 104, 110, 69, 66, 68,
                 84, 89, 72, 80, 55, 75, 87, 57, 106, 69, 66, 62, 102, 76, 111, 999, 96, 83,
                 84, 61, 102, 63, 107, 63, 76, 58, 83, 58, 61, 71, 77, 90, 74, 100, 103, 74,
                 92, 102, 63, 87, 93, 61, 63, 86, 74, 98, 64, 999, 78, 95, 84, 81, 107, 85,
                 79, 82, 89, 65, 107, 57, 74, 77, 97, 92, 58, 96, 105, 60, 55, 74, 57, 80,
                 62, 85, 87, 62, 999, 71, 74, 70, 97, 59, 82, 96, 105, 70, 89, 105, 60, 70,
                 87, 999, 64, 108, 107, 104, 85, 95, 108, 74, 64, 97, 89, 88, 79, 67, 81, 92,
                 63, 80, 76, 94, 104, 67, 73, 61, 99, 96, 68, 90, 86, 79, 85, 111, 75, 98,
                 81, 111, 108, 103, 85, 72, 108, 102, 999, 64, 107, 112, 66, 93, 89, 78, 66, 92,
                 63, 101, 92, 64, 72, 56, 71, 64, 87, 78, 107, 85, 109, 95, 69, 111, 64, 72,
                 55, 66, 99, 57, 78, 55, 58, 90, 88, 71, 90, 103, 92, 98, 67, 97, 77, 68,
                 77, 59, 78, 69, 77, 81, 61, 99, 999, 85, 78, 104, 97, 95, 74, 70, 69, 83,
                 68, 68, 77, 60, 85, 82, 93, 66, 71, 62, 64, 107, 999, 65, 78, 59, 83, 67,
                 108,  58,  95, 106,  83,  79,  67,  59,  96,  90,  55,  55,  96, 109,  82,  55, 101,  58,
                 97, 77, 60, 81, 999, 81, 75, 100, 66, 65, 105, 94, 101, 56, 999, 59, 105, 59,
                 93, 56, 104, 74, 81, 62, 76, 65, 107, 60, 107, 98, 77, 86, 83, 104, 74, 69,
                 97, 80, 91, 56, 108, 87, 65, 91, 93, 60, 91, 110, 107, 88, 96, 70, 60, 99,
                 66, 91, 107, 65, 81, 109, 84, 106, 80, 92, 78, 84, 91, 59])

eta_filtrate = ages[ages != 999]
print("Età valide totali:", len(eta_filtrate), "\n")

eta_massima = eta_filtrate.max()
print("Età massima (escludendo 999):", eta_massima)

Età valide totali: 486 

Età massima (escludendo 999): 112


### 9.**Generazione random di storie**

Usando la lista qui sotto, estrai casualmente **5 parole con reinserimento** (cioè, i duplicati sono ammessi).  

Successivamente, inserisci casualmente queste parole negli spazi vuoti (indicati con "_") nella seguente frase:

*"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico __ che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il __ come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "__".  
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un __.  
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.  
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza _!" Ci fu grande gioia e celebrazione."*


In [30]:
lista_parole = [
    'INSEDIAMENTO', 'SEPARAZIONE', 'DIFFERENZA', 'APPLICAZIONE', 'ATTEGGIAMENTO', 'VERDURA', 'IMPERO', 'RICEVIMENTO',
    'IGNORANZA', 'BIOGRAFIA', 'VISIONE', 'AGENTE DI POLIZIA', 'PROVA', 'PRESTAZIONE', 'PRESENTAZIONE', 'PARENTE',
    'GIUSTIFICAZIONE', 'FILOSOFIA', 'DIREZIONE', 'BENEFICIARIO', 'BATTERIA', 'CERIMONIA', 'AGONIA', 'RECUPERO',
    'ALFABETIZZAZIONE', 'CONSEGNA', 'SERBATOIO', 'VOLONTARIO', 'DEPOSITO', 'BIRILLO DA BOWLING', 'NEMICO', 'ANNUNCIO',
    'CARAMELLA ZUCCHERATA', 'FULMINE', 'PALLONCINO', 'COPERTA', 'SCOPERTA', 'PENALITÀ', 'GENERALE', 'ALPACA',
    'VANTAGGIO', 'HOT DOG', 'ABITO', 'MATEMATICA', 'VARIANTE'
]

scelte = np.random.choice(lista_parole, size=5, replace=True)
print("Parole scelte:", scelte, "\n")

storia = f'''"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico {scelte[0]} che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il {scelte[1]} come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "{scelte[2]}".  
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un {scelte[3]}.  
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.  
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza {scelte[4]}!" Ci fu grande gioia e celebrazione."'''

print(storia)



Parole scelte: ['APPLICAZIONE' 'ALFABETIZZAZIONE' 'PRESTAZIONE' 'IGNORANZA' 'CONSEGNA'] 

"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico APPLICAZIONE che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il ALFABETIZZAZIONE come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "PRESTAZIONE".  
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un IGNORANZA.  
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.  
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza CONSEGNA!" Ci fu grande gioia e celebrazione."


Esempio di output


"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico APPLICAZIONE che proteggeva. 
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante 
e le offrì il DEPOSITO come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "PRESTAZIONE".  

Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un BIRILLO DA BOWLING. 
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo. 
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: 
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza GIUSTIFICAZIONE!"  

Ci fu grande gioia e celebrazione."